### ISSUE TITLE
Diamond pattern star pattern java c++ .under hacktoberfest2022

### ISSUE THREAD

**Issue by avnishkt** [coderoshan18093/Beginner_Hactoberfest2022#154]
diamond pattern under hacktoberfest2022

**Comment by sejal-phatangare** [comment]
Sejal Phatangare
Cummins College of Engineering, Pune
Computer Department
Please assign this issue to me

**Comment by Himani-Patil** [comment]
Hey, Can you assign this issue to me?

**Comment by pujapkc** [comment]
Hey,Can you assign this issue to me ?

**Comment by ayushrathore111** [comment]
i wanna work on this
