### ISSUE TITLE
Rock Paper Scissors.py

### ISSUE THREAD

**Issue by gshraddha17** [coderoshan18093/Beginner_Hactoberfest2022#16]
I want to add a Rock Paper Scissors game which uses speech and voice recognition techniques. Please can I be assigned this issue.

**Comment by coderoshan18093** [comment]
Go ahead

**Comment by gshraddha17** [comment]
I have made a PR. Kindly merge it.

**Comment by Deepanshu1008** [comment]
Please assign me this task.
